# Generated by Django 4.1.2 on 2022-10-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author_en_post_author_fa_post_category_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_fa',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at_fa',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at_jalali_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at_jalali_fa',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_description_fa',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_title_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_title_fa',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug_fa',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_alt_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_alt_fa',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_fa',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at_fa',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at_jalali_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at_jalali_fa',
        ),
    ]
