# Generated by Django 4.1.2 on 2022-10-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_author_en_remove_post_author_fa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status_fa',
        ),
    ]
